# -*- coding: utf-8 -*-
"""proyecto_final_equipo2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12e7Rqgkl1zZ215P90b7YsXecMYQd5TST

# Equipo 2
## Miembros:
### Jorge Arturo Torres Cruz - A01176590

## Recolección de datos
"""

url_files = ['wines.txt', 'bubble_gums.txt', 'dumplings.txt', 'pizza_urls.txt', 'sandwich.txt']

# Iteramos por cada uno de los archivos y obtenemos los URLs de las imagenes.
print("Reading files containing images urls")
urls = []
for file_name in url_files:
  with open(file_name) as f:
    content = f.readlines()
    content = [url.strip() for url in content]
    print("Reading {} image urls ({})".format(len(content), file_name))
    urls.append(content)

# Utilizaremos urllib para descargar las imagenes utilizando URLs obtenidos de ImageNet
import urllib.request
import os

categories = ['wine', 'bubble_gum', 'dumplings', 'pizza', 'sandwich']
os.mkdir("./data")
for idx, category in enumerate(categories):
  counter = 0
  try:
    print("Creating directory to store {} images".format(category))
    os.mkdir("./data/{}".format(category))
  except Exception as e:
    print(e)
  else:
    print("Succesfully created {}/ directory".format(category))
  for img in range(0, len(urls[idx])):
    try:
      urllib.request.urlretrieve(urls[idx][img], "{}/{}.jpg".format(category, counter))
      counter += 1
    except Exception as e:
      print("==>An error ocurred while fetching img #{} from {}".format(img, category))
      print(e)

